export const columnData = {
    "data": [
        {
            "id": 1,
            "createdOn": 1699442924653,
            "createdBy": null,
            "updatedOn": 1699442924653,
            "updatedBy": null,
            "flag": "ACTIVE",
            "tableName": "Claim",
            "tableType": "TABLE",
            "schemaName": "test_database1",
            "tableCatalog": "WorkSpace",
            "columnList": [
                {
                    "id": 1,
                    "createdOn": 1699442924696,
                    "createdBy": null,
                    "updatedOn": 1699442924696,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "ClaimeeID",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "NO",
                    "ordinalPosition": 1
                },
                {
                    "id": 2,
                    "createdOn": 1699442924700,
                    "createdBy": null,
                    "updatedOn": 1699442924700,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "FirstName",
                    "datatype": "varchar",
                    "maximumCharacterLength": 50,
                    "isNullable": "YES",
                    "ordinalPosition": 2
                },
                {
                    "id": 3,
                    "createdOn": 1699442924701,
                    "createdBy": null,
                    "updatedOn": 1699442924745,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "Cust_ID",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "YES",
                    "ordinalPosition": 3
                }
            ]
        },
        {
            "id": 2,
            "createdOn": 1699442924703,
            "createdBy": null,
            "updatedOn": 1699442924703,
            "updatedBy": null,
            "flag": "ACTIVE",
            "tableName": "Customer",
            "tableType": "TABLE",
            "schemaName": "test_database1",
            "tableCatalog": "WorkSpace",
            "columnList": [
                {
                    "id": 4,
                    "createdOn": 1699442924705,
                    "createdBy": null,
                    "updatedOn": 1699442924705,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "CIF",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "NO",
                    "ordinalPosition": 1
                },
                {
                    "id": 5,
                    "createdOn": 1699442924706,
                    "createdBy": null,
                    "updatedOn": 1699442924706,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "FirstName",
                    "datatype": "varchar",
                    "maximumCharacterLength": 50,
                    "isNullable": "YES",
                    "ordinalPosition": 2
                }
            ]
        },
        {
            "id": 3,
            "createdOn": 1699442924709,
            "createdBy": null,
            "updatedOn": 1699442924709,
            "updatedBy": null,
            "flag": "ACTIVE",
            "tableName": "OrderItems",
            "tableType": "TABLE",
            "schemaName": "test_database1",
            "tableCatalog": "WorkSpace",
            "columnList": [
                {
                    "id": 6,
                    "createdOn": 1699442924710,
                    "createdBy": null,
                    "updatedOn": 1699442924710,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "OrderItemID",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "NO",
                    "ordinalPosition": 1
                },
                {
                    "id": 9,
                    "createdOn": 1699442924715,
                    "createdBy": null,
                    "updatedOn": 1699442924715,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "Quantity",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "YES",
                    "ordinalPosition": 4
                },
                {
                    "id": 7,
                    "createdOn": 1699442924712,
                    "createdBy": null,
                    "updatedOn": 1699442924748,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "abc",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "YES",
                    "ordinalPosition": 2
                },
                {
                    "id": 8,
                    "createdOn": 1699442924713,
                    "createdBy": null,
                    "updatedOn": 1699442924748,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "ProductID",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "YES",
                    "ordinalPosition": 3
                }
            ]
        },
        {
            "id": 4,
            "createdOn": 1699442924717,
            "createdBy": null,
            "updatedOn": 1699442924717,
            "updatedBy": null,
            "flag": "ACTIVE",
            "tableName": "Orders",
            "tableType": "TABLE",
            "schemaName": "test_database1",
            "tableCatalog": "WorkSpace",
            "columnList": [
                {
                    "id": 10,
                    "createdOn": 1699442924718,
                    "createdBy": null,
                    "updatedOn": 1699442924718,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "OrderID",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "NO",
                    "ordinalPosition": 1
                },
                {
                    "id": 11,
                    "createdOn": 1699442924720,
                    "createdBy": null,
                    "updatedOn": 1699442924720,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "ProductID",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "NO",
                    "ordinalPosition": 2
                },
                {
                    "id": 12,
                    "createdOn": 1699442924722,
                    "createdBy": null,
                    "updatedOn": 1699442924722,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "Quantity",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "YES",
                    "ordinalPosition": 3
                }
            ]
        },
        {
            "id": 5,
            "createdOn": 1699442924723,
            "createdBy": null,
            "updatedOn": 1699442924723,
            "updatedBy": null,
            "flag": "ACTIVE",
            "tableName": "Policy",
            "tableType": "TABLE",
            "schemaName": "test_database1",
            "tableCatalog": "WorkSpace",
            "columnList": [
                {
                    "id": 13,
                    "createdOn": 1699442924725,
                    "createdBy": null,
                    "updatedOn": 1699442924725,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "Cust_ID",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "NO",
                    "ordinalPosition": 1
                },
                {
                    "id": 14,
                    "createdOn": 1699442924726,
                    "createdBy": null,
                    "updatedOn": 1699442924726,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "FirstName",
                    "datatype": "varchar",
                    "maximumCharacterLength": 50,
                    "isNullable": "YES",
                    "ordinalPosition": 2
                },
                {
                    "id": 15,
                    "createdOn": 1699442924727,
                    "createdBy": null,
                    "updatedOn": 1699442924727,
                    "updatedBy": null,
                    "flag": "ACTIVE",
                    "statisticList": [],
                    "dbMetadataTable": null,
                    "columnName": "CIF",
                    "datatype": "int",
                    "maximumCharacterLength": 10,
                    "isNullable": "YES",
                    "ordinalPosition": 3
                }
            ]
        }
    ],
    "message": null,
    "code": null
}
